toolbox:
  enabled: true

cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false

    nodes:
      - name: "deb2"
        devices:
          - name: "sdb"
      - name: "deb3" 
        devices:
          - name: "sdb"
      - name: "deb4"
        devices:
          - name: "sdb"