# rook-cluster-values.yaml
operatorNamespace: rook-ceph
cephClusterSpec:
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "deb2"
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "deb3" 
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "deb4"
      devices:
      - name: "sdb"
        config:
          osdsPerDevice: "1"
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  network:
    provider: host
  healthCheck:
    daemonHealth:
      mon:
        timeout: 2m
      osd:
        timeout: 2m
      status:
        timeout: 2m