operatorNamespace: rook-ceph

cephClusterSpec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
    createPrometheusRules: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "sda|sdb"
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: rook-ceph