operatorNamespace: rook-ceph

toolbox:
  enabled: true

csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  enableGrpcMetrics: true
  enablePluginSocketDir: true

monitoring:
  enabled: true
  createPrometheusRules: true
  createServiceMonitor: true