toolbox:
  enabled: true

cephClusterSpec:
  configOverride: |
    [global]
    osd_pool_default_pg_num = 8
    osd_pool_default_pgp_num = 8

  storage:
    useAllNodes: false
    useAllDevices: false

    nodes:
      - name: "deb2"
        devices:
          - name: "sdb"
      - name: "deb3" 
        devices:
          - name: "sdb"
      - name: "deb4"
        devices:
          - name: "sdb"